name: transfer

agents:
  intent:
    class: IntentAgent
    card: agents/intent_agent/card.json

  slot:
    class: SlotFillerAgent
    card: agents/slot_filler_agent/card.json

  interaction:
    class: InteractionAgent
    card: agents/interaction_agent/card.json

  execute:
    class: TransferExecuteAgent
    card: agents/transfer_execute_agent/card.json

flows:
  router: flows.router.TransferFlowRouter
  handlers:
    DEFAULT_FLOW: flows.handlers.DefaultFlowHandler
    TRANSFER_FLOW: flows.handlers.TransferFlowHandler

state:
  model: state.models.TransferState
  manager: state.state_manager.TransferStateManager
