# 최소 템플릿: interaction만 필수, 단일 flow, BaseState
name: minimal

agents:
  interaction:
<<<<<<< HEAD
    class: InteractionAgent
    card: agents/interaction_agent/card.json
=======
    class: agents.interaction_agent.agent.InteractionAgent
>>>>>>> 54bcbbf (claude ver1.)
    stream: true

flows:
  router: flows.router.MinimalFlowRouter
  handlers:
    DEFAULT_FLOW: flows.handlers.MinimalFlowHandler

state:
  manager: state.state_manager.MinimalStateManager
